spring:
  application:
      name: Auth

  datasource:
    url: jdbc:mysql://localhost:3306/user
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update
application:
  jwt:
    secret: abcdefghijklmnopqrstuvwxyz1234567890
    expiration: 86400000
    refreshExpiration: 604800000