spring:
  application:
      name: Auth

  datasource:
    url: jdbc:mysql://localhost:3306/user
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
application:
  jwt:
    expiration: 86400000
    refreshExpiration: 604800000